#ifndef COMPILE_HEARTBEAT_READER_H
#define COMPILE_HEARTBEAT_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct ej_compile_Heartbeat_table *ej_compile_Heartbeat_table_t;
typedef struct ej_compile_Heartbeat_table *ej_compile_Heartbeat_mutable_table_t;
typedef const flatbuffers_uoffset_t *ej_compile_Heartbeat_vec_t;
typedef flatbuffers_uoffset_t *ej_compile_Heartbeat_mutable_vec_t;
#ifndef ej_compile_Heartbeat_file_identifier
#define ej_compile_Heartbeat_file_identifier 0
#endif
/* deprecated, use ej_compile_Heartbeat_file_identifier */
#ifndef ej_compile_Heartbeat_identifier
#define ej_compile_Heartbeat_identifier 0
#endif
#define ej_compile_Heartbeat_type_hash ((flatbuffers_thash_t)0x5b43835b)
#define ej_compile_Heartbeat_type_identifier "\x5b\x83\x43\x5b"
#ifndef ej_compile_Heartbeat_file_extension
#define ej_compile_Heartbeat_file_extension "bin"
#endif



struct ej_compile_Heartbeat_table { uint8_t unused__; };

static inline size_t ej_compile_Heartbeat_vec_len(ej_compile_Heartbeat_vec_t vec)
__flatbuffers_vec_len(vec)
static inline ej_compile_Heartbeat_table_t ej_compile_Heartbeat_vec_at(ej_compile_Heartbeat_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(ej_compile_Heartbeat_table_t, vec, i, 0)
__flatbuffers_table_as_root(ej_compile_Heartbeat)

__flatbuffers_define_scalar_field(0, ej_compile_Heartbeat, timestamp_ms, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_scalar_field(1, ej_compile_Heartbeat, last_handled_request_ms, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_scalar_field(2, ej_compile_Heartbeat, start_time_ms, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_scalar_field(3, ej_compile_Heartbeat, accumulated_ms, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_scalar_field(4, ej_compile_Heartbeat, request_count, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_string_field(5, ej_compile_Heartbeat, instance_id, 0)
__flatbuffers_define_string_field(6, ej_compile_Heartbeat, queue, 0)
__flatbuffers_define_string_field(7, ej_compile_Heartbeat, ip_address, 0)
__flatbuffers_define_scalar_field(8, ej_compile_Heartbeat, pid, flatbuffers_int32, int32_t, INT32_C(0))


#include "flatcc/flatcc_epilogue.h"
#endif /* COMPILE_HEARTBEAT_READER_H */
