#ifndef COMPILE_HEARTBEAT_VERIFIER_H
#define COMPILE_HEARTBEAT_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef COMPILE_HEARTBEAT_READER_H
#include "compile_heartbeat_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int ej_compile_Heartbeat_verify_table(flatcc_table_verifier_descriptor_t *td);

static int ej_compile_Heartbeat_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* timestamp_ms */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* last_handled_request_ms */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* start_time_ms */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 8, 8) /* accumulated_ms */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 8, 8) /* request_count */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 5, 0) /* instance_id */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 6, 0) /* queue */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 7, 0) /* ip_address */)) return ret;
    return flatcc_verify_ok;
}

static inline int ej_compile_Heartbeat_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, ej_compile_Heartbeat_identifier, &ej_compile_Heartbeat_verify_table);
}

static inline int ej_compile_Heartbeat_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, ej_compile_Heartbeat_type_identifier, &ej_compile_Heartbeat_verify_table);
}

static inline int ej_compile_Heartbeat_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &ej_compile_Heartbeat_verify_table);
}

static inline int ej_compile_Heartbeat_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &ej_compile_Heartbeat_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* COMPILE_HEARTBEAT_VERIFIER_H */
