#!/bin/sh -x

exec ./configure --prefix=/home/cher/inst-ejudge  --with-reuse=/home/cher/new-reuse  --enable-charset=koi8-r --with-httpd-cgi-bin-dir=/home/httpd/cgi-bin --with-httpd-htdocs-dir=/home/httpd/html --with-dcc=/usr/local/pkg/kylix3-links/dcc --with-festival=/usr/local/pkg/festival-1.95/festival --with-javac=/usr/local/java/bin/javac --with-scheme=/usr/local/pkg/drscheme/bin/mzscheme --with-mysql=/usr/local/pkg/mysql --with-fpc=/usr/local/pkg/fpc/bin/fpc --enable-ajax  --enable-hidden-server-bins --enable-local-dir=/var/lib/ejudge --enable-werror "$@"
