CREATE TABLE reviews(
    serial_id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    review_uuid CHAR(36) NOT NULL UNIQUE KEY,
    run_serial_id BIGINT NOT NULL,
    contest_id INT NOT NULL,
    run_id INT NOT NULL,
    generation INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 0,
    creation_time DATETIME(6) NOT NULL,
    purpose TINYINT NOT NULL,
    last_update_time DATETIME(6) DEFAULT NULL,
    request_user_id INT DEFAULT NULL,
    moderator_user_id INT DEFAULT NULL,
    moderation_time DATETIME(6) DEFAULT NULL,
    moderation_text TEXT DEFAULT NULL,
    review_source MEDIUMTEXT DEFAULT NULL,
    review_source_sha256 CHAR(64) DEFAULT NULL,
    reviewer_user_id INT DEFAULT NULL,
    review_start_time DATETIME(6) DEFAULT NULL,
    review_agent VARCHAR(255) DEFAULT NULL,
    review_heartbeat_time DATETIME(6) DEFAULT NULL,
    review_heartbeat_status VARCHAR(255) DEFAULT NULL,
    review_finish_time DATETIME(6) DEFAULT NULL,
    review_result MEDIUMTEXT DEFAULT NULL,
    review_judge_result MEDIUMTEXT DEFAULT NULL,
    review_recommended_status TINYINT DEFAULT NULL,
    review_statistics TEXT DEFAULT NULL,
    approver_user_id INT DEFAULT NULL,
    approval_time DATETIME(6) DEFAULT NULL,
    approved_text TEXT DEFAULT NULL,
    approver_review_mark TINYINT DEFAULT NULL,
    user_opened_time DATETIME(6) DEFAULT NULL,
    user_opened_count INT DEFAULT NULL,
    user_review_mark TINYINT DEFAULT NULL,
    input_tokens INT DEFAULT NULL,
    cached_input_tokens INT DEFAULT NULL,
    output_tokens INT DEFAULT NULL,
    reasoning_tokens INT DEFAULT NULL,
    total_tokens INT DEFAULT NULL,
    model VARCHAR(127) DEFAULT NULL,
    review_approved_as_is TINYINT(1) DEFAULT NULL,
    status_approved_as_is TINYINT(1) DEFAULT NULL,
    ai_generation_score TINYINT DEFAULT NULL,
    UNIQUE KEY reviews_generation_idx (contest_id, run_id, generation),
    KEY reviews_run_serial_idx (run_serial_id),
    KEY reviews_requested_idx (request_user_id),
    KEY reviews_moderator_idx (moderator_user_id),
    KEY reviews_reviewer_idx (reviewer_user_id),
    KEY reviews_approver_idx (approver_user_id),
    KEY reviews_contest_status_idx (contest_id, status),
    KEY reviews_status_create_time_idx (status, creation_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
