CREATE TABLE reviews(
    serial_id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    review_uuid CHAR(40) NOT NULL UNIQUE KEY,
    run_serial_id BIGINT NOT NULL,
    contest_id INT UNSIGNED NOT NULL,
    run_id INT UNSIGNED NOT NULL,
    generation INT NOT NULL DEFAULT 0,
    status INT NOT NULL DEFAULT 0,
    create_time DATETIME(6) NOT NULL,
    purpose INT NOT NULL,
    last_update_time DATETIME(6) DEFAULT NULL,
    requested_by INT UNSIGNED DEFAULT NULL,
    moderator_user_id INT UNSIGNED DEFAULT NULL,
    moderation_time DATETIME(6) DEFAULT NULL,
    moderation_text TEXT DEFAULT NULL,
    review_source MEDIUMTEXT DEFAULT NULL,
    review_source_sha256 VARCHAR(64) DEFAULT NULL,
    review_start_time DATETIME(6) DEFAULT NULL,
    review_agent VARCHAR(512) DEFAULT NULL,
    review_finish_time DATETIME(6) DEFAULT NULL,
    review_result MEDIUMTEXT DEFAULT NULL,
    review_content_type VARCHAR(64) DEFAULT NULL,
    review_recommended_status INT DEFAULT NULL,
    review_statistics TEXT DEFAULT NULL,
    approver_user_id INT UNSIGNED DEFAULT NULL,
    approve_time DATETIME(6) DEFAULT NULL,
    approved_text TEXT DEFAULT NULL,
    approver_review_mark INT DEFAULT NULL,
    user_open_time DATETIME(6) DEFAULT NULL,
    user_open_count INT DEFAULT NULL,
    user_review_mark INT DEFAULT NULL,
    input_tokens INT DEFAULT NULL,
    cached_input_tokens INT DEFAULT NULL,
    output_tokens INT DEFAULT NULL,
    reasoning_tokens INT DEFAULT NULL,
    total_tokens INT DEFAULT NULL,
    model VARCHAR(128) DEFAULT NULL,
    UNIQUE KEY reviews_generation_idx (contest_id, run_id, generation),
    KEY reviews_run_idx (contest_id, run_id),
    KEY reviews_contest_id_idx (contest_id),
    KEY reviews_requested_idx (requested_by),
    KEY reviews_moderator_idx (moderator_user_id),
    KEY reviews_approver_idx (approver_user_id),
    KEY reviews_contest_status_idx (contest_id, status),
    KEY reviews_status_idx (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
