#!/bin/sh -x

exec ./configure --prefix=/home/cher/inst-ejudge  --with-reuse=/home/cher/reuse  --enable-ejudge-xml=/home/judges/data/ejudge.xml --enable-charset=koi8-r --enable-socket-path=/tmp/userlist-socket --enable-contests-dir=/home/judges/data/contests
