#!/bin/sh -x

exec ./configure --prefix=/home/cher/inst-ejudge  --with-reuse=/home/cher/new-reuse  --enable-charset=koi8-r --enable-socket-path=/tmp/userlist-socket --enable-contests-home-dir=/home/judges --enable-conf-dir=/home/judges/data --enable-cgi-conf-dir=../cgi-data --with-httpd-cgi-bin-dir=/home/httpd/cgi-bin --with-httpd-htdocs-dir=/home/httpd/html --with-fpc=/usr/local/pkg/fpc-1.0.10/bin/fpc --with-festival=/usr/local/pkg/festival-1.95/festival --with-javac=/usr/local/java/bin/javac --with-scheme=/usr/local/pkg/drscheme-2.08/bin/mzscheme $@
