#!/bin/sh -x

exec ./configure --prefix=/home/cher/inst-ejudge  --with-reuse=/home/cher/reuse  --enable-charset=koi8-r --with-httpd-cgi-bin-dir=/home/httpd/cgi-bin --with-httpd-htdocs-dir=/home/httpd/html --enable-ajax --enable-hidden-server-bins --enable-local-dir=/var/lib/ejudge "$@"
