/* -*- c -*- */
/* $Id$ */
#ifndef __SUPER_ACTIONS_H__
#define __SUPER_ACTIONS_H__

/* Copyright (C) 2004,2005 Alexander Chernov <cher@ispras.ru> */

/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

enum
{
  SUPER_ACTION_VIEW_CONTEST = 1,
  SUPER_ACTION_OPEN_CONTEST,
  SUPER_ACTION_CLOSE_CONTEST,
  SUPER_ACTION_SERVE_MNG_TEMP,        /* ! */
  SUPER_ACTION_SERVE_MNG,             /* ! */
  SUPER_ACTION_SERVE_MNG_RESUME,      /* ! */
  SUPER_ACTION_SERVE_MNG_STOP,        /* ! */
  SUPER_ACTION_SERVE_MNG_SUSPEND,     /* ! */
  SUPER_ACTION_SERVE_MNG_PROBE_RUN,   /* ! */
  SUPER_ACTION_SERVE_MNG_RESET_ERROR, /* ! */
  SUPER_ACTION_SERVE_MNG_TERM,     /* ! */
  SUPER_ACTION_SERVE_LOG_TRUNC,    /* ! */
  SUPER_ACTION_SERVE_LOG_DEV_NULL, /* ! */
  SUPER_ACTION_SERVE_LOG_FILE,  /* ! */
  SUPER_ACTION_SERVE_LOG_VIEW,
  SUPER_ACTION_RUN_MNG_TEMP,        /* ! */
  SUPER_ACTION_RUN_MNG,             /* ! */
  SUPER_ACTION_RUN_MNG_RESUME,      /* ! */
  SUPER_ACTION_RUN_MNG_STOP,        /* ! */
  SUPER_ACTION_RUN_MNG_SUSPEND,     /* ! */
  SUPER_ACTION_RUN_MNG_PROBE_RUN,   /* ! */
  SUPER_ACTION_RUN_MNG_RESET_ERROR, /* ! */
  SUPER_ACTION_RUN_MNG_TERM,     /* ! */
  SUPER_ACTION_RUN_LOG_TRUNC,    /* ! */
  SUPER_ACTION_RUN_LOG_DEV_NULL, /* ! */
  SUPER_ACTION_RUN_LOG_FILE,     /* ! */
  SUPER_ACTION_RUN_LOG_VIEW,
  SUPER_ACTION_CONTEST_RESTART, /* ! */
  SUPER_ACTION_LOGOUT,
  SUPER_ACTION_CONTEST_VISIBLE,
  SUPER_ACTION_CONTEST_INVISIBLE,
  SUPER_ACTION_VIEW_CONTEST_XML,
  SUPER_ACTION_VIEW_SERVE_CFG,
  SUPER_ACTION_HIDE_HIDDEN,
  SUPER_ACTION_SHOW_HIDDEN,
  SUPER_ACTION_HIDE_CLOSED,
  SUPER_ACTION_SHOW_CLOSED,
  SUPER_ACTION_HIDE_UNMNG,
  SUPER_ACTION_SHOW_UNMNG,
  SUPER_ACTION_RESTART,         /* ! */
  SUPER_ACTION_CREATE_CONTEST,
  SUPER_ACTION_CREATE_CONTEST_2,
  SUPER_ACTION_CNTS_CHANGE_NAME,
  SUPER_ACTION_CNTS_CLEAR_NAME,
  SUPER_ACTION_CNTS_CHANGE_NAME_EN,
  SUPER_ACTION_CNTS_CLEAR_NAME_EN,
  SUPER_ACTION_CNTS_CHANGE_AUTOREGISTER,
  SUPER_ACTION_CNTS_CHANGE_TEAM_PASSWD,
  SUPER_ACTION_CNTS_CHANGE_MANAGED,
  SUPER_ACTION_CNTS_CHANGE_RUN_MANAGED,
  SUPER_ACTION_CNTS_CHANGE_CLEAN_USERS,
  SUPER_ACTION_CNTS_CHANGE_CLOSED,
  SUPER_ACTION_CNTS_CHANGE_INVISIBLE,
  SUPER_ACTION_CNTS_CHANGE_TIME_SKEW,
  SUPER_ACTION_CNTS_CHANGE_TEAM_LOGIN,
  SUPER_ACTION_CNTS_BASIC_VIEW,
  SUPER_ACTION_CNTS_ADVANCED_VIEW,
  SUPER_ACTION_CNTS_CHANGE_DEADLINE,
  SUPER_ACTION_CNTS_CLEAR_DEADLINE,
  SUPER_ACTION_CNTS_CHANGE_USERS_HEADER,
  SUPER_ACTION_CNTS_CLEAR_USERS_HEADER,
  SUPER_ACTION_CNTS_EDIT_USERS_HEADER,
  SUPER_ACTION_CNTS_CHANGE_USERS_FOOTER,
  SUPER_ACTION_CNTS_CLEAR_USERS_FOOTER,
  SUPER_ACTION_CNTS_EDIT_USERS_FOOTER,
  SUPER_ACTION_CNTS_CHANGE_REGISTER_HEADER,
  SUPER_ACTION_CNTS_CLEAR_REGISTER_HEADER,
  SUPER_ACTION_CNTS_EDIT_REGISTER_HEADER,
  SUPER_ACTION_CNTS_CHANGE_REGISTER_FOOTER,
  SUPER_ACTION_CNTS_CLEAR_REGISTER_FOOTER,
  SUPER_ACTION_CNTS_EDIT_REGISTER_FOOTER,
  SUPER_ACTION_CNTS_CHANGE_TEAM_HEADER,
  SUPER_ACTION_CNTS_CLEAR_TEAM_HEADER,
  SUPER_ACTION_CNTS_EDIT_TEAM_HEADER,
  SUPER_ACTION_CNTS_CHANGE_TEAM_FOOTER,
  SUPER_ACTION_CNTS_CLEAR_TEAM_FOOTER,
  SUPER_ACTION_CNTS_EDIT_TEAM_FOOTER,
  SUPER_ACTION_CNTS_CHANGE_USERS_HEAD_STYLE,
  SUPER_ACTION_CNTS_CLEAR_USERS_HEAD_STYLE,
  SUPER_ACTION_CNTS_CHANGE_USERS_PAR_STYLE,
  SUPER_ACTION_CNTS_CLEAR_USERS_PAR_STYLE,
  SUPER_ACTION_CNTS_CHANGE_USERS_TABLE_STYLE,
  SUPER_ACTION_CNTS_CLEAR_USERS_TABLE_STYLE,
  SUPER_ACTION_CNTS_CHANGE_USERS_VERB_STYLE,
  SUPER_ACTION_CNTS_CLEAR_USERS_VERB_STYLE,
  SUPER_ACTION_CNTS_CHANGE_REGISTER_HEAD_STYLE,
  SUPER_ACTION_CNTS_CLEAR_REGISTER_HEAD_STYLE,
  SUPER_ACTION_CNTS_CHANGE_REGISTER_PAR_STYLE,
  SUPER_ACTION_CNTS_CLEAR_REGISTER_PAR_STYLE,
  SUPER_ACTION_CNTS_CHANGE_REGISTER_TABLE_STYLE,
  SUPER_ACTION_CNTS_CLEAR_REGISTER_TABLE_STYLE,
  SUPER_ACTION_CNTS_CHANGE_TEAM_HEAD_STYLE,
  SUPER_ACTION_CNTS_CLEAR_TEAM_HEAD_STYLE,
  SUPER_ACTION_CNTS_CHANGE_TEAM_PAR_STYLE,
  SUPER_ACTION_CNTS_CLEAR_TEAM_PAR_STYLE,
  SUPER_ACTION_CNTS_HIDE_HTML_ATTRS,
  SUPER_ACTION_CNTS_SHOW_HTML_ATTRS,
  SUPER_ACTION_CNTS_HIDE_HTML_HEADERS,
  SUPER_ACTION_CNTS_SHOW_HTML_HEADERS,
  SUPER_ACTION_EDIT_CURRENT_CONTEST,
  SUPER_ACTION_CNTS_CHANGE_REGISTER_EMAIL,
  SUPER_ACTION_CNTS_CLEAR_REGISTER_EMAIL,
  SUPER_ACTION_CNTS_CHANGE_REGISTER_URL,
  SUPER_ACTION_CNTS_CLEAR_REGISTER_URL,
  SUPER_ACTION_CNTS_CHANGE_REGISTER_EMAIL_FILE,
  SUPER_ACTION_CNTS_CLEAR_REGISTER_EMAIL_FILE,
  SUPER_ACTION_CNTS_EDIT_REGISTER_EMAIL_FILE,
  SUPER_ACTION_CNTS_FORGET,
  SUPER_ACTION_CNTS_COMMIT,
  SUPER_ACTION_CNTS_CHANGE_TEAM_URL,
  SUPER_ACTION_CNTS_CLEAR_TEAM_URL,
  SUPER_ACTION_CNTS_CHANGE_STANDINGS_URL,
  SUPER_ACTION_CNTS_CLEAR_STANDINGS_URL,
  SUPER_ACTION_CNTS_CHANGE_PROBLEMS_URL,
  SUPER_ACTION_CNTS_CLEAR_PROBLEMS_URL,
  SUPER_ACTION_CNTS_HIDE_PATHS,
  SUPER_ACTION_CNTS_SHOW_PATHS,
  SUPER_ACTION_CNTS_CHANGE_ROOT_DIR,
  SUPER_ACTION_CNTS_CLEAR_ROOT_DIR,
  SUPER_ACTION_CNTS_CHANGE_CONF_DIR,
  SUPER_ACTION_CNTS_CLEAR_CONF_DIR,
  SUPER_ACTION_CNTS_HIDE_ACCESS_RULES,
  SUPER_ACTION_CNTS_SHOW_ACCESS_RULES,
  SUPER_ACTION_CNTS_EDIT_REGISTER_ACCESS,
  SUPER_ACTION_CNTS_EDIT_USERS_ACCESS,
  SUPER_ACTION_CNTS_EDIT_MASTER_ACCESS,
  SUPER_ACTION_CNTS_EDIT_JUDGE_ACCESS,
  SUPER_ACTION_CNTS_EDIT_TEAM_ACCESS,
  SUPER_ACTION_CNTS_EDIT_SERVE_CONTROL_ACCESS,
  SUPER_ACTION_CNTS_DEFAULT_ACCESS,
  SUPER_ACTION_CNTS_CHANGE_RULE,
  SUPER_ACTION_CNTS_DELETE_RULE,
  SUPER_ACTION_CNTS_UP_RULE,
  SUPER_ACTION_CNTS_DOWN_RULE,
  SUPER_ACTION_CNTS_ADD_RULE,
  SUPER_ACTION_CNTS_HIDE_PERMISSIONS,
  SUPER_ACTION_CNTS_SHOW_PERMISSIONS,
  SUPER_ACTION_CNTS_EDIT_PERMISSION,
  SUPER_ACTION_CNTS_ADD_PERMISSION,
  SUPER_ACTION_CNTS_DELETE_PERMISSION,
  SUPER_ACTION_EDIT_CONTEST_XML,
  SUPER_ACTION_CNTS_SAVE_PERMISSIONS,
  SUPER_ACTION_CNTS_HIDE_FORM_FIELDS,
  SUPER_ACTION_CNTS_SHOW_FORM_FIELDS,
  SUPER_ACTION_CNTS_EDIT_FORM_FIELDS,
  SUPER_ACTION_CNTS_EDIT_CONTESTANT_FIELDS,
  SUPER_ACTION_CNTS_EDIT_RESERVE_FIELDS,
  SUPER_ACTION_CNTS_EDIT_COACH_FIELDS,
  SUPER_ACTION_CNTS_EDIT_ADVISOR_FIELDS,
  SUPER_ACTION_CNTS_EDIT_GUEST_FIELDS,
  SUPER_ACTION_CNTS_SAVE_FORM_FIELDS,
  SUPER_ACTION_CNTS_SAVE_CONTESTANT_FIELDS,
  SUPER_ACTION_CNTS_SAVE_RESERVE_FIELDS,
  SUPER_ACTION_CNTS_SAVE_COACH_FIELDS,
  SUPER_ACTION_CNTS_SAVE_ADVISOR_FIELDS,
  SUPER_ACTION_CNTS_SAVE_GUEST_FIELDS,
  SUPER_ACTION_CNTS_SAVE_USERS_HEADER,
  SUPER_ACTION_CNTS_SAVE_USERS_FOOTER,
  SUPER_ACTION_CNTS_SAVE_REGISTER_HEADER,
  SUPER_ACTION_CNTS_SAVE_REGISTER_FOOTER,
  SUPER_ACTION_CNTS_SAVE_TEAM_HEADER,
  SUPER_ACTION_CNTS_SAVE_TEAM_FOOTER,
  SUPER_ACTION_CNTS_SAVE_REGISTER_EMAIL_FILE,
  SUPER_ACTION_CNTS_READ_USERS_HEADER,
  SUPER_ACTION_CNTS_READ_USERS_FOOTER,
  SUPER_ACTION_CNTS_READ_REGISTER_HEADER,
  SUPER_ACTION_CNTS_READ_REGISTER_FOOTER,
  SUPER_ACTION_CNTS_READ_TEAM_HEADER,
  SUPER_ACTION_CNTS_READ_TEAM_FOOTER,
  SUPER_ACTION_CNTS_READ_REGISTER_EMAIL_FILE,
  SUPER_ACTION_CNTS_CLEAR_USERS_HEADER_TEXT,
  SUPER_ACTION_CNTS_CLEAR_USERS_FOOTER_TEXT,
  SUPER_ACTION_CNTS_CLEAR_REGISTER_HEADER_TEXT,
  SUPER_ACTION_CNTS_CLEAR_REGISTER_FOOTER_TEXT,
  SUPER_ACTION_CNTS_CLEAR_TEAM_HEADER_TEXT,
  SUPER_ACTION_CNTS_CLEAR_TEAM_FOOTER_TEXT,
  SUPER_ACTION_CNTS_CLEAR_REGISTER_EMAIL_FILE_TEXT,

  SUPER_ACTION_LAST,
};

#endif /* __SUPER_ACTIONS_H__ */
