#!/bin/sh -x

exec ./configure --prefix=/home/cher/inst-ejudge  --with-reuse=/home/cher/reuse  --enable-charset=utf-8 --with-httpd-cgi-bin-dir=/home/httpd/cgi-bin --with-httpd-htdocs-dir=/home/httpd/sites --enable-ajax --enable-local-dir=/var/lib/ejudge --enable-werror "$@"
