/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_X86 1
#undef  CONFIG_SBUS
#define CONFIG_UID16 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#undef  CONFIG_MODVERSIONS
#define CONFIG_KMOD 1

/*
 * Processor type and features
 */
#undef  CONFIG_M386
#undef  CONFIG_M486
#undef  CONFIG_M586
#undef  CONFIG_M586TSC
#undef  CONFIG_M586MMX
#undef  CONFIG_M686
#undef  CONFIG_MPENTIUMIII
#define CONFIG_MPENTIUM4 1
#undef  CONFIG_MK6
#undef  CONFIG_MK7
#undef  CONFIG_MK8
#undef  CONFIG_MELAN
#undef  CONFIG_MCRUSOE
#undef  CONFIG_MWINCHIPC6
#undef  CONFIG_MWINCHIP2
#undef  CONFIG_MWINCHIP3D
#undef  CONFIG_MCYRIXIII
#undef  CONFIG_MVIAC3_2
#define CONFIG_X86_WP_WORKS_OK 1
#define CONFIG_X86_INVLPG 1
#define CONFIG_X86_CMPXCHG 1
#define CONFIG_X86_XADD 1
#define CONFIG_X86_BSWAP 1
#define CONFIG_X86_POPAD_OK 1
#undef  CONFIG_RWSEM_GENERIC_SPINLOCK
#define CONFIG_RWSEM_XCHGADD_ALGORITHM 1
#define CONFIG_X86_L1_CACHE_SHIFT (7)
#define CONFIG_X86_HAS_TSC 1
#define CONFIG_X86_GOOD_APIC 1
#define CONFIG_X86_PGE 1
#define CONFIG_X86_USE_PPRO_CHECKSUM 1
#define CONFIG_X86_F00F_WORKS_OK 1
#define CONFIG_X86_MCE 1
#undef  CONFIG_TOSHIBA
#undef  CONFIG_I8K
#undef  CONFIG_MICROCODE
#define CONFIG_MICROCODE_MODULE 1
#undef  CONFIG_X86_MSR
#define CONFIG_X86_MSR_MODULE 1
#undef  CONFIG_X86_CPUID
#define CONFIG_X86_CPUID_MODULE 1
#define CONFIG_NOHIGHMEM 1
#undef  CONFIG_HIGHMEM4G
#undef  CONFIG_HIGHMEM64G
#undef  CONFIG_HIGHMEM
#undef  CONFIG_MATH_EMULATION
#define CONFIG_MTRR 1
#undef  CONFIG_SMP
#define CONFIG_X86_UP_APIC 1
#define CONFIG_X86_UP_IOAPIC 1
#define CONFIG_X86_LOCAL_APIC 1
#define CONFIG_X86_IO_APIC 1
#undef  CONFIG_X86_TSC_DISABLE
#define CONFIG_X86_TSC 1

/*
 * General setup
 */
#define CONFIG_NET 1
#define CONFIG_PCI 1
#undef  CONFIG_PCI_GOBIOS
#undef  CONFIG_PCI_GODIRECT
#define CONFIG_PCI_GOANY 1
#define CONFIG_PCI_BIOS 1
#define CONFIG_PCI_DIRECT 1
#define CONFIG_ISA 1
#define CONFIG_PCI_NAMES 1
#undef  CONFIG_EISA
#undef  CONFIG_MCA
#define CONFIG_HOTPLUG 1

/*
 * PCMCIA/CardBus support
 */
#undef  CONFIG_PCMCIA
#define CONFIG_PCMCIA_MODULE 1
#define CONFIG_CARDBUS 1
#define CONFIG_TCIC 1
#define CONFIG_I82092 1
#define CONFIG_I82365 1

/*
 * PCI Hotplug Support
 */
#undef  CONFIG_HOTPLUG_PCI
#undef  CONFIG_HOTPLUG_PCI_COMPAQ
#undef  CONFIG_HOTPLUG_PCI_COMPAQ_NVRAM
#undef  CONFIG_HOTPLUG_PCI_IBM
#undef  CONFIG_HOTPLUG_PCI_ACPI
#define CONFIG_SYSVIPC 1
#define CONFIG_BSD_PROCESS_ACCT 1
#define CONFIG_SYSCTL 1
#define CONFIG_KCORE_ELF 1
#undef  CONFIG_KCORE_AOUT
#undef  CONFIG_BINFMT_AOUT
#define CONFIG_BINFMT_AOUT_MODULE 1
#define CONFIG_BINFMT_ELF 1
#undef  CONFIG_BINFMT_ELF_AOUT
#undef  CONFIG_BINFMT_MISC
#define CONFIG_BINFMT_MISC_MODULE 1
#undef  CONFIG_PM
#undef  CONFIG_APM

/*
 * ACPI Support
 */
#define CONFIG_ACPI 1
#undef  CONFIG_ACPI_HT_ONLY
#define CONFIG_ACPI_BOOT 1
#define CONFIG_ACPI_BUS 1
#define CONFIG_ACPI_INTERPRETER 1
#define CONFIG_ACPI_EC 1
#define CONFIG_ACPI_POWER 1
#define CONFIG_ACPI_PCI 1
#define CONFIG_ACPI_SLEEP 1
#define CONFIG_ACPI_SYSTEM 1
#undef  CONFIG_ACPI_AC
#define CONFIG_ACPI_AC_MODULE 1
#undef  CONFIG_ACPI_BATTERY
#define CONFIG_ACPI_BATTERY_MODULE 1
#undef  CONFIG_ACPI_BUTTON
#define CONFIG_ACPI_BUTTON_MODULE 1
#undef  CONFIG_ACPI_FAN
#define CONFIG_ACPI_FAN_MODULE 1
#undef  CONFIG_ACPI_PROCESSOR
#define CONFIG_ACPI_PROCESSOR_MODULE 1
#undef  CONFIG_ACPI_THERMAL
#define CONFIG_ACPI_THERMAL_MODULE 1
#undef  CONFIG_ACPI_ASUS
#define CONFIG_ACPI_ASUS_MODULE 1
#undef  CONFIG_ACPI_TOSHIBA
#define CONFIG_ACPI_DEBUG 1
#undef  CONFIG_ACPI_RELAXED_AML

/*
 * Memory Technology Devices (MTD)
 */
#undef  CONFIG_MTD

/*
 * Parallel port support
 */
#undef  CONFIG_PARPORT
#define CONFIG_PARPORT_MODULE 1
#undef  CONFIG_PARPORT_PC
#define CONFIG_PARPORT_PC_MODULE 1
#undef  CONFIG_PARPORT_PC_CML1
#define CONFIG_PARPORT_PC_CML1_MODULE 1
#undef  CONFIG_PARPORT_SERIAL
#define CONFIG_PARPORT_PC_FIFO 1
#undef  CONFIG_PARPORT_PC_SUPERIO
#undef  CONFIG_PARPORT_PC_PCMCIA
#undef  CONFIG_PARPORT_AMIGA
#undef  CONFIG_PARPORT_MFC3
#undef  CONFIG_PARPORT_ATARI
#undef  CONFIG_PARPORT_GSC
#undef  CONFIG_PARPORT_SUNBPP
#undef  CONFIG_PARPORT_OTHER
#define CONFIG_PARPORT_1284 1

/*
 * Plug and Play configuration
 */
#define CONFIG_PNP 1
#define CONFIG_ISAPNP 1

/*
 * Block devices
 */
#undef  CONFIG_BLK_DEV_FD
#define CONFIG_BLK_DEV_FD_MODULE 1
#undef  CONFIG_BLK_DEV_XD
#undef  CONFIG_PARIDE
#undef  CONFIG_BLK_CPQ_DA
#undef  CONFIG_BLK_CPQ_CISS_DA
#undef  CONFIG_CISS_SCSI_TAPE
#undef  CONFIG_BLK_DEV_DAC960
#undef  CONFIG_BLK_DEV_UMEM
#undef  CONFIG_BLK_DEV_LOOP
#define CONFIG_BLK_DEV_LOOP_MODULE 1
#undef  CONFIG_BLK_DEV_NBD
#define CONFIG_BLK_DEV_NBD_MODULE 1
#undef  CONFIG_BLK_DEV_RAM
#define CONFIG_BLK_DEV_RAM_MODULE 1
#define CONFIG_BLK_DEV_RAM_SIZE (4096)
#undef  CONFIG_BLK_DEV_INITRD
#define CONFIG_BLK_STATS 1

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#undef  CONFIG_BLK_DEV_MD
#define CONFIG_BLK_DEV_MD_MODULE 1
#undef  CONFIG_MD_LINEAR
#define CONFIG_MD_LINEAR_MODULE 1
#undef  CONFIG_MD_RAID0
#define CONFIG_MD_RAID0_MODULE 1
#undef  CONFIG_MD_RAID1
#define CONFIG_MD_RAID1_MODULE 1
#undef  CONFIG_MD_RAID5
#define CONFIG_MD_RAID5_MODULE 1
#undef  CONFIG_MD_MULTIPATH
#define CONFIG_MD_MULTIPATH_MODULE 1
#undef  CONFIG_BLK_DEV_LVM
#define CONFIG_BLK_DEV_LVM_MODULE 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#undef  CONFIG_NETLINK_DEV
#define CONFIG_NETLINK_DEV_MODULE 1
#define CONFIG_NETFILTER 1
#define CONFIG_NETFILTER_DEBUG 1
#define CONFIG_FILTER 1
#define CONFIG_UNIX 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#undef  CONFIG_IP_ADVANCED_ROUTER
#undef  CONFIG_IP_PNP
#undef  CONFIG_NET_IPIP
#define CONFIG_NET_IPIP_MODULE 1
#undef  CONFIG_NET_IPGRE
#define CONFIG_NET_IPGRE_MODULE 1
#undef  CONFIG_NET_IPGRE_BROADCAST
#undef  CONFIG_IP_MROUTE
#define CONFIG_ARPD 1
#define CONFIG_INET_ECN 1
#define CONFIG_SYN_COOKIES 1

/*
 *   IP: Netfilter Configuration
 */
#undef  CONFIG_IP_NF_CONNTRACK
#define CONFIG_IP_NF_CONNTRACK_MODULE 1
#undef  CONFIG_IP_NF_FTP
#define CONFIG_IP_NF_FTP_MODULE 1
#undef  CONFIG_IP_NF_AMANDA
#define CONFIG_IP_NF_AMANDA_MODULE 1
#undef  CONFIG_IP_NF_TFTP
#define CONFIG_IP_NF_TFTP_MODULE 1
#undef  CONFIG_IP_NF_IRC
#define CONFIG_IP_NF_IRC_MODULE 1
#undef  CONFIG_IP_NF_QUEUE
#define CONFIG_IP_NF_QUEUE_MODULE 1
#undef  CONFIG_IP_NF_IPTABLES
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#undef  CONFIG_IP_NF_MATCH_LIMIT
#define CONFIG_IP_NF_MATCH_LIMIT_MODULE 1
#undef  CONFIG_IP_NF_MATCH_MAC
#define CONFIG_IP_NF_MATCH_MAC_MODULE 1
#undef  CONFIG_IP_NF_MATCH_PKTTYPE
#define CONFIG_IP_NF_MATCH_PKTTYPE_MODULE 1
#undef  CONFIG_IP_NF_MATCH_MARK
#define CONFIG_IP_NF_MATCH_MARK_MODULE 1
#undef  CONFIG_IP_NF_MATCH_MULTIPORT
#define CONFIG_IP_NF_MATCH_MULTIPORT_MODULE 1
#undef  CONFIG_IP_NF_MATCH_TOS
#define CONFIG_IP_NF_MATCH_TOS_MODULE 1
#undef  CONFIG_IP_NF_MATCH_RECENT
#define CONFIG_IP_NF_MATCH_RECENT_MODULE 1
#undef  CONFIG_IP_NF_MATCH_ECN
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#undef  CONFIG_IP_NF_MATCH_DSCP
#define CONFIG_IP_NF_MATCH_DSCP_MODULE 1
#undef  CONFIG_IP_NF_MATCH_AH_ESP
#define CONFIG_IP_NF_MATCH_AH_ESP_MODULE 1
#undef  CONFIG_IP_NF_MATCH_LENGTH
#define CONFIG_IP_NF_MATCH_LENGTH_MODULE 1
#undef  CONFIG_IP_NF_MATCH_TTL
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#undef  CONFIG_IP_NF_MATCH_TCPMSS
#define CONFIG_IP_NF_MATCH_TCPMSS_MODULE 1
#undef  CONFIG_IP_NF_MATCH_HELPER
#define CONFIG_IP_NF_MATCH_HELPER_MODULE 1
#undef  CONFIG_IP_NF_MATCH_STATE
#define CONFIG_IP_NF_MATCH_STATE_MODULE 1
#undef  CONFIG_IP_NF_MATCH_CONNTRACK
#define CONFIG_IP_NF_MATCH_CONNTRACK_MODULE 1
#undef  CONFIG_IP_NF_MATCH_UNCLEAN
#define CONFIG_IP_NF_MATCH_UNCLEAN_MODULE 1
#undef  CONFIG_IP_NF_MATCH_OWNER
#define CONFIG_IP_NF_MATCH_OWNER_MODULE 1
#undef  CONFIG_IP_NF_FILTER
#define CONFIG_IP_NF_FILTER_MODULE 1
#undef  CONFIG_IP_NF_TARGET_REJECT
#define CONFIG_IP_NF_TARGET_REJECT_MODULE 1
#undef  CONFIG_IP_NF_TARGET_MIRROR
#define CONFIG_IP_NF_TARGET_MIRROR_MODULE 1
#undef  CONFIG_IP_NF_NAT
#define CONFIG_IP_NF_NAT_MODULE 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#undef  CONFIG_IP_NF_TARGET_MASQUERADE
#define CONFIG_IP_NF_TARGET_MASQUERADE_MODULE 1
#undef  CONFIG_IP_NF_TARGET_REDIRECT
#define CONFIG_IP_NF_TARGET_REDIRECT_MODULE 1
#undef  CONFIG_IP_NF_NAT_AMANDA
#define CONFIG_IP_NF_NAT_AMANDA_MODULE 1
#undef  CONFIG_IP_NF_NAT_LOCAL
#undef  CONFIG_IP_NF_NAT_SNMP_BASIC
#define CONFIG_IP_NF_NAT_SNMP_BASIC_MODULE 1
#undef  CONFIG_IP_NF_NAT_IRC
#define CONFIG_IP_NF_NAT_IRC_MODULE 1
#undef  CONFIG_IP_NF_NAT_FTP
#define CONFIG_IP_NF_NAT_FTP_MODULE 1
#undef  CONFIG_IP_NF_NAT_TFTP
#define CONFIG_IP_NF_NAT_TFTP_MODULE 1
#undef  CONFIG_IP_NF_MANGLE
#define CONFIG_IP_NF_MANGLE_MODULE 1
#undef  CONFIG_IP_NF_TARGET_TOS
#define CONFIG_IP_NF_TARGET_TOS_MODULE 1
#undef  CONFIG_IP_NF_TARGET_ECN
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#undef  CONFIG_IP_NF_TARGET_DSCP
#define CONFIG_IP_NF_TARGET_DSCP_MODULE 1
#undef  CONFIG_IP_NF_TARGET_MARK
#define CONFIG_IP_NF_TARGET_MARK_MODULE 1
#undef  CONFIG_IP_NF_TARGET_LOG
#define CONFIG_IP_NF_TARGET_LOG_MODULE 1
#undef  CONFIG_IP_NF_TARGET_ULOG
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#undef  CONFIG_IP_NF_TARGET_TCPMSS
#define CONFIG_IP_NF_TARGET_TCPMSS_MODULE 1
#undef  CONFIG_IP_NF_ARPTABLES
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#undef  CONFIG_IP_NF_ARPFILTER
#define CONFIG_IP_NF_ARPFILTER_MODULE 1
#undef  CONFIG_IP_NF_ARP_MANGLE
#define CONFIG_IP_NF_ARP_MANGLE_MODULE 1
#undef  CONFIG_IP_NF_COMPAT_IPCHAINS
#undef  CONFIG_IP_NF_COMPAT_IPFWADM
#undef  CONFIG_IPV6
#define CONFIG_IPV6_MODULE 1

/*
 *   IPv6: Netfilter Configuration
 */
#undef  CONFIG_IP6_NF_QUEUE
#define CONFIG_IP6_NF_QUEUE_MODULE 1
#undef  CONFIG_IP6_NF_IPTABLES
#define CONFIG_IP6_NF_IPTABLES_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_LIMIT
#define CONFIG_IP6_NF_MATCH_LIMIT_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_MAC
#define CONFIG_IP6_NF_MATCH_MAC_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_RT
#define CONFIG_IP6_NF_MATCH_RT_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_OPTS
#define CONFIG_IP6_NF_MATCH_OPTS_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_FRAG
#define CONFIG_IP6_NF_MATCH_FRAG_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_HL
#define CONFIG_IP6_NF_MATCH_HL_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_MULTIPORT
#define CONFIG_IP6_NF_MATCH_MULTIPORT_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_OWNER
#define CONFIG_IP6_NF_MATCH_OWNER_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_MARK
#define CONFIG_IP6_NF_MATCH_MARK_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_IPV6HEADER
#define CONFIG_IP6_NF_MATCH_IPV6HEADER_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_AHESP
#define CONFIG_IP6_NF_MATCH_AHESP_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_LENGTH
#define CONFIG_IP6_NF_MATCH_LENGTH_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_EUI64
#define CONFIG_IP6_NF_MATCH_EUI64_MODULE 1
#undef  CONFIG_IP6_NF_FILTER
#define CONFIG_IP6_NF_FILTER_MODULE 1
#undef  CONFIG_IP6_NF_TARGET_LOG
#define CONFIG_IP6_NF_TARGET_LOG_MODULE 1
#undef  CONFIG_IP6_NF_MANGLE
#define CONFIG_IP6_NF_MANGLE_MODULE 1
#undef  CONFIG_IP6_NF_TARGET_MARK
#define CONFIG_IP6_NF_TARGET_MARK_MODULE 1
#undef  CONFIG_KHTTPD
#undef  CONFIG_ATM
#undef  CONFIG_VLAN_8021Q

/*
 *  
 */
#undef  CONFIG_IPX
#define CONFIG_IPX_MODULE 1
#undef  CONFIG_IPX_INTERN
#undef  CONFIG_ATALK

/*
 * Appletalk devices
 */
#undef  CONFIG_DEV_APPLETALK
#undef  CONFIG_DECNET
#undef  CONFIG_BRIDGE
#undef  CONFIG_X25
#undef  CONFIG_LAPB
#undef  CONFIG_LLC
#undef  CONFIG_NET_DIVERT
#undef  CONFIG_ECONET
#undef  CONFIG_WAN_ROUTER
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_HW_FLOWCONTROL

/*
 * QoS and/or fair queueing
 */
#undef  CONFIG_NET_SCHED

/*
 * Network testing
 */
#undef  CONFIG_NET_PKTGEN

/*
 * Telephony Support
 */
#undef  CONFIG_PHONE
#undef  CONFIG_PHONE_IXJ
#undef  CONFIG_PHONE_IXJ_PCMCIA

/*
 * ATA/IDE/MFM/RLL support
 */
#define CONFIG_IDE 1

/*
 * IDE, ATA and ATAPI Block devices
 */
#define CONFIG_BLK_DEV_IDE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef  CONFIG_BLK_DEV_HD_IDE
#undef  CONFIG_BLK_DEV_HD
#define CONFIG_BLK_DEV_IDEDISK 1
#define CONFIG_IDEDISK_MULTI_MODE 1
#undef  CONFIG_IDEDISK_STROKE
#undef  CONFIG_BLK_DEV_IDECS
#undef  CONFIG_BLK_DEV_IDECD
#define CONFIG_BLK_DEV_IDECD_MODULE 1
#undef  CONFIG_BLK_DEV_IDETAPE
#undef  CONFIG_BLK_DEV_IDEFLOPPY
#undef  CONFIG_BLK_DEV_IDESCSI
#define CONFIG_BLK_DEV_IDESCSI_MODULE 1
#define CONFIG_IDE_TASK_IOCTL 1

/*
 * IDE chipset support/bugfixes
 */
#undef  CONFIG_BLK_DEV_CMD640
#undef  CONFIG_BLK_DEV_CMD640_ENHANCED
#undef  CONFIG_BLK_DEV_ISAPNP
#define CONFIG_BLK_DEV_IDEPCI 1
#undef  CONFIG_BLK_DEV_GENERIC
#define CONFIG_IDEPCI_SHARE_IRQ 1
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#undef  CONFIG_BLK_DEV_OFFBOARD
#undef  CONFIG_BLK_DEV_IDEDMA_FORCED
#define CONFIG_IDEDMA_PCI_AUTO 1
#undef  CONFIG_IDEDMA_ONLYDISK
#define CONFIG_BLK_DEV_IDEDMA 1
#undef  CONFIG_IDEDMA_PCI_WIP
#undef  CONFIG_BLK_DEV_ADMA100
#undef  CONFIG_BLK_DEV_AEC62XX
#undef  CONFIG_BLK_DEV_ALI15X3
#undef  CONFIG_WDC_ALI15X3
#undef  CONFIG_BLK_DEV_AMD74XX
#undef  CONFIG_AMD74XX_OVERRIDE
#undef  CONFIG_BLK_DEV_CMD64X
#undef  CONFIG_BLK_DEV_TRIFLEX
#undef  CONFIG_BLK_DEV_CY82C693
#undef  CONFIG_BLK_DEV_CS5530
#undef  CONFIG_BLK_DEV_HPT34X
#undef  CONFIG_HPT34X_AUTODMA
#undef  CONFIG_BLK_DEV_HPT366
#define CONFIG_BLK_DEV_PIIX 1
#undef  CONFIG_BLK_DEV_NS87415
#undef  CONFIG_BLK_DEV_OPTI621
#undef  CONFIG_BLK_DEV_PDC202XX_OLD
#undef  CONFIG_PDC202XX_BURST
#undef  CONFIG_BLK_DEV_PDC202XX_NEW
#undef  CONFIG_BLK_DEV_RZ1000
#undef  CONFIG_BLK_DEV_SC1200
#undef  CONFIG_BLK_DEV_SVWKS
#undef  CONFIG_BLK_DEV_SIIMAGE
#undef  CONFIG_BLK_DEV_SIS5513
#undef  CONFIG_BLK_DEV_SLC90E66
#undef  CONFIG_BLK_DEV_TRM290
#undef  CONFIG_BLK_DEV_VIA82CXXX
#undef  CONFIG_IDE_CHIPSETS
#define CONFIG_IDEDMA_AUTO 1
#undef  CONFIG_IDEDMA_IVB
#undef  CONFIG_DMA_NONPCI
#define CONFIG_BLK_DEV_IDE_MODES 1
#undef  CONFIG_BLK_DEV_ATARAID
#undef  CONFIG_BLK_DEV_ATARAID_PDC
#undef  CONFIG_BLK_DEV_ATARAID_HPT
#undef  CONFIG_BLK_DEV_ATARAID_SII

/*
 * SCSI support
 */
#undef  CONFIG_SCSI
#define CONFIG_SCSI_MODULE 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#undef  CONFIG_BLK_DEV_SD
#define CONFIG_BLK_DEV_SD_MODULE 1
#define CONFIG_SD_EXTRA_DEVS (40)
#undef  CONFIG_CHR_DEV_ST
#undef  CONFIG_CHR_DEV_OSST
#undef  CONFIG_BLK_DEV_SR
#define CONFIG_BLK_DEV_SR_MODULE 1
#define CONFIG_BLK_DEV_SR_VENDOR 1
#define CONFIG_SR_EXTRA_DEVS (2)
#undef  CONFIG_CHR_DEV_SG
#define CONFIG_CHR_DEV_SG_MODULE 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#define CONFIG_SCSI_DEBUG_QUEUES 1
#define CONFIG_SCSI_MULTI_LUN 1
#define CONFIG_SCSI_CONSTANTS 1
#define CONFIG_SCSI_LOGGING 1

/*
 * SCSI low-level drivers
 */
#undef  CONFIG_BLK_DEV_3W_XXXX_RAID
#undef  CONFIG_SCSI_7000FASST
#undef  CONFIG_SCSI_ACARD
#undef  CONFIG_SCSI_AHA152X
#undef  CONFIG_SCSI_AHA1542
#undef  CONFIG_SCSI_AHA1740
#undef  CONFIG_SCSI_AACRAID
#undef  CONFIG_SCSI_AIC7XXX
#undef  CONFIG_SCSI_AIC79XX
#undef  CONFIG_SCSI_AIC7XXX_OLD
#undef  CONFIG_SCSI_DPT_I2O
#undef  CONFIG_SCSI_ADVANSYS
#undef  CONFIG_SCSI_IN2000
#undef  CONFIG_SCSI_AM53C974
#undef  CONFIG_SCSI_MEGARAID
#undef  CONFIG_SCSI_BUSLOGIC
#undef  CONFIG_SCSI_CPQFCTS
#undef  CONFIG_SCSI_DMX3191D
#undef  CONFIG_SCSI_DTC3280
#undef  CONFIG_SCSI_EATA
#undef  CONFIG_SCSI_EATA_DMA
#undef  CONFIG_SCSI_EATA_PIO
#undef  CONFIG_SCSI_FUTURE_DOMAIN
#undef  CONFIG_SCSI_GDTH
#undef  CONFIG_SCSI_GENERIC_NCR5380
#undef  CONFIG_SCSI_IPS
#undef  CONFIG_SCSI_INITIO
#undef  CONFIG_SCSI_INIA100
#undef  CONFIG_SCSI_PPA
#undef  CONFIG_SCSI_IMM
#undef  CONFIG_SCSI_NCR53C406A
#undef  CONFIG_SCSI_NCR53C7xx
#undef  CONFIG_SCSI_SYM53C8XX_2
#undef  CONFIG_SCSI_NCR53C8XX
#undef  CONFIG_SCSI_SYM53C8XX
#undef  CONFIG_SCSI_PAS16
#undef  CONFIG_SCSI_PCI2000
#undef  CONFIG_SCSI_PCI2220I
#undef  CONFIG_SCSI_PSI240I
#undef  CONFIG_SCSI_QLOGIC_FAS
#undef  CONFIG_SCSI_QLOGIC_ISP
#undef  CONFIG_SCSI_QLOGIC_FC
#undef  CONFIG_SCSI_QLOGIC_1280
#undef  CONFIG_SCSI_SEAGATE
#undef  CONFIG_SCSI_SIM710
#undef  CONFIG_SCSI_SYM53C416
#undef  CONFIG_SCSI_DC390T
#undef  CONFIG_SCSI_T128
#undef  CONFIG_SCSI_U14_34F
#undef  CONFIG_SCSI_ULTRASTOR
#undef  CONFIG_SCSI_NSP32
#undef  CONFIG_SCSI_DEBUG

/*
 * PCMCIA SCSI adapter support
 */
#undef  CONFIG_SCSI_PCMCIA

/*
 * Fusion MPT device support
 */
#undef  CONFIG_FUSION
#undef  CONFIG_FUSION_BOOT
#undef  CONFIG_FUSION_ISENSE
#undef  CONFIG_FUSION_CTL
#undef  CONFIG_FUSION_LAN

/*
 * IEEE 1394 (FireWire) support (EXPERIMENTAL)
 */
#undef  CONFIG_IEEE1394

/*
 * I2O device support
 */
#undef  CONFIG_I2O
#undef  CONFIG_I2O_PCI
#undef  CONFIG_I2O_BLOCK
#undef  CONFIG_I2O_LAN
#undef  CONFIG_I2O_SCSI
#undef  CONFIG_I2O_PROC

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1

/*
 * ARCnet devices
 */
#undef  CONFIG_ARCNET
#undef  CONFIG_DUMMY
#define CONFIG_DUMMY_MODULE 1
#undef  CONFIG_BONDING
#define CONFIG_BONDING_MODULE 1
#undef  CONFIG_EQUALIZER
#define CONFIG_EQUALIZER_MODULE 1
#undef  CONFIG_TUN
#define CONFIG_TUN_MODULE 1
#undef  CONFIG_ETHERTAP
#define CONFIG_ETHERTAP_MODULE 1
#undef  CONFIG_NET_SB1000
#define CONFIG_NET_SB1000_MODULE 1

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#undef  CONFIG_SUNLANCE
#undef  CONFIG_HAPPYMEAL
#undef  CONFIG_SUNBMAC
#undef  CONFIG_SUNQE
#undef  CONFIG_SUNGEM
#define CONFIG_NET_VENDOR_3COM 1
#undef  CONFIG_EL1
#undef  CONFIG_EL2
#undef  CONFIG_ELPLUS
#undef  CONFIG_EL16
#undef  CONFIG_EL3
#undef  CONFIG_3C515
#undef  CONFIG_ELMC
#undef  CONFIG_ELMC_II
#undef  CONFIG_VORTEX
#define CONFIG_VORTEX_MODULE 1
#undef  CONFIG_TYPHOON
#define CONFIG_TYPHOON_MODULE 1
#undef  CONFIG_LANCE
#define CONFIG_LANCE_MODULE 1
#define CONFIG_NET_VENDOR_SMC 1
#undef  CONFIG_WD80x3
#undef  CONFIG_ULTRAMCA
#undef  CONFIG_ULTRA
#undef  CONFIG_ULTRA32
#undef  CONFIG_SMC9194
#define CONFIG_SMC9194_MODULE 1
#undef  CONFIG_NET_VENDOR_RACAL
#undef  CONFIG_AT1700
#undef  CONFIG_DEPCA
#undef  CONFIG_HP100
#define CONFIG_HP100_MODULE 1
#undef  CONFIG_NET_ISA
#define CONFIG_NET_PCI 1
#undef  CONFIG_PCNET32
#define CONFIG_PCNET32_MODULE 1
#undef  CONFIG_AMD8111_ETH
#define CONFIG_AMD8111_ETH_MODULE 1
#undef  CONFIG_ADAPTEC_STARFIRE
#undef  CONFIG_AC3200
#undef  CONFIG_APRICOT
#undef  CONFIG_B44
#undef  CONFIG_CS89x0
#undef  CONFIG_TULIP
#define CONFIG_TULIP_MODULE 1
#undef  CONFIG_TULIP_MWI
#undef  CONFIG_TULIP_MMIO
#undef  CONFIG_DE4X5
#define CONFIG_DE4X5_MODULE 1
#undef  CONFIG_DGRS
#define CONFIG_DGRS_MODULE 1
#undef  CONFIG_DM9102
#undef  CONFIG_EEPRO100
#define CONFIG_EEPRO100_MODULE 1
#undef  CONFIG_EEPRO100_PIO
#undef  CONFIG_E100
#define CONFIG_E100_MODULE 1
#undef  CONFIG_LNE390
#undef  CONFIG_FEALNX
#undef  CONFIG_NATSEMI
#undef  CONFIG_NE2K_PCI
#define CONFIG_NE2K_PCI_MODULE 1
#undef  CONFIG_NE3210
#undef  CONFIG_ES3210
#undef  CONFIG_8139CP
#define CONFIG_8139CP_MODULE 1
#undef  CONFIG_8139TOO
#define CONFIG_8139TOO_MODULE 1
#undef  CONFIG_8139TOO_PIO
#undef  CONFIG_8139TOO_TUNE_TWISTER
#undef  CONFIG_8139TOO_8129
#undef  CONFIG_8139_OLD_RX_RESET
#undef  CONFIG_SIS900
#undef  CONFIG_EPIC100
#undef  CONFIG_SUNDANCE
#undef  CONFIG_SUNDANCE_MMIO
#undef  CONFIG_TLAN
#define CONFIG_TLAN_MODULE 1
#undef  CONFIG_VIA_RHINE
#undef  CONFIG_VIA_RHINE_MMIO
#undef  CONFIG_WINBOND_840
#define CONFIG_WINBOND_840_MODULE 1
#undef  CONFIG_NET_POCKET

/*
 * Ethernet (1000 Mbit)
 */
#undef  CONFIG_ACENIC
#undef  CONFIG_DL2K
#undef  CONFIG_E1000
#undef  CONFIG_MYRI_SBUS
#undef  CONFIG_NS83820
#undef  CONFIG_HAMACHI
#undef  CONFIG_YELLOWFIN
#undef  CONFIG_R8169
#undef  CONFIG_SK98LIN
#undef  CONFIG_TIGON3
#undef  CONFIG_FDDI
#undef  CONFIG_HIPPI
#undef  CONFIG_PLIP
#define CONFIG_PLIP_MODULE 1
#undef  CONFIG_PPP
#define CONFIG_PPP_MODULE 1
#define CONFIG_PPP_MULTILINK 1
#define CONFIG_PPP_FILTER 1
#undef  CONFIG_PPP_ASYNC
#define CONFIG_PPP_ASYNC_MODULE 1
#undef  CONFIG_PPP_SYNC_TTY
#define CONFIG_PPP_SYNC_TTY_MODULE 1
#undef  CONFIG_PPP_DEFLATE
#define CONFIG_PPP_DEFLATE_MODULE 1
#undef  CONFIG_PPP_BSDCOMP
#define CONFIG_PPP_BSDCOMP_MODULE 1
#undef  CONFIG_PPPOE
#define CONFIG_PPPOE_MODULE 1
#undef  CONFIG_SLIP
#define CONFIG_SLIP_MODULE 1
#define CONFIG_SLIP_COMPRESSED 1
#define CONFIG_SLIP_SMART 1
#undef  CONFIG_SLIP_MODE_SLIP6

/*
 * Wireless LAN (non-hamradio)
 */
#undef  CONFIG_NET_RADIO

/*
 * Token Ring devices
 */
#undef  CONFIG_TR
#undef  CONFIG_NET_FC
#undef  CONFIG_RCPCI
#undef  CONFIG_SHAPER

/*
 * Wan interfaces
 */
#undef  CONFIG_WAN

/*
 * PCMCIA network device support
 */
#define CONFIG_NET_PCMCIA 1
#undef  CONFIG_PCMCIA_3C589
#undef  CONFIG_PCMCIA_3C574
#undef  CONFIG_PCMCIA_FMVJ18X
#undef  CONFIG_PCMCIA_PCNET
#define CONFIG_PCMCIA_PCNET_MODULE 1
#undef  CONFIG_PCMCIA_AXNET
#undef  CONFIG_PCMCIA_NMCLAN
#undef  CONFIG_PCMCIA_SMC91C92
#undef  CONFIG_PCMCIA_XIRC2PS
#undef  CONFIG_ARCNET_COM20020_CS
#undef  CONFIG_PCMCIA_IBMTR
#undef  CONFIG_PCMCIA_XIRCOM
#undef  CONFIG_PCMCIA_XIRTULIP
#define CONFIG_NET_PCMCIA_RADIO 1
#undef  CONFIG_PCMCIA_RAYCS
#define CONFIG_PCMCIA_RAYCS_MODULE 1
#undef  CONFIG_PCMCIA_NETWAVE
#undef  CONFIG_PCMCIA_WAVELAN
#undef  CONFIG_AIRONET4500_CS

/*
 * Amateur Radio support
 */
#undef  CONFIG_HAMRADIO

/*
 * IrDA (infrared) support
 */
#undef  CONFIG_IRDA

/*
 * ISDN subsystem
 */
#undef  CONFIG_ISDN

/*
 * Old CD-ROM drivers (not SCSI, not IDE)
 */
#undef  CONFIG_CD_NO_IDESCSI

/*
 * Input core support
 */
#undef  CONFIG_INPUT
#define CONFIG_INPUT_MODULE 1
#undef  CONFIG_INPUT_KEYBDEV
#define CONFIG_INPUT_KEYBDEV_MODULE 1
#undef  CONFIG_INPUT_MOUSEDEV
#define CONFIG_INPUT_MOUSEDEV_MODULE 1
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X (1280)
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y (1024)
#undef  CONFIG_INPUT_JOYDEV
#define CONFIG_INPUT_JOYDEV_MODULE 1
#undef  CONFIG_INPUT_EVDEV
#define CONFIG_INPUT_EVDEV_MODULE 1

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#undef  CONFIG_SERIAL
#define CONFIG_SERIAL_MODULE 1
#undef  CONFIG_SERIAL_EXTENDED
#undef  CONFIG_SERIAL_NONSTANDARD
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_UNIX98_PTY_COUNT (256)
#undef  CONFIG_PRINTER
#define CONFIG_PRINTER_MODULE 1
#undef  CONFIG_LP_CONSOLE
#undef  CONFIG_PPDEV
#undef  CONFIG_TIPAR

/*
 * I2C support
 */
#undef  CONFIG_I2C

/*
 * Mice
 */
#undef  CONFIG_BUSMOUSE
#define CONFIG_MOUSE 1
#define CONFIG_PSMOUSE 1
#undef  CONFIG_82C710_MOUSE
#undef  CONFIG_PC110_PAD
#undef  CONFIG_MK712_MOUSE

/*
 * Joysticks
 */
#undef  CONFIG_INPUT_GAMEPORT
#undef  CONFIG_INPUT_NS558
#undef  CONFIG_INPUT_LIGHTNING
#undef  CONFIG_INPUT_PCIGAME
#undef  CONFIG_INPUT_CS461X
#undef  CONFIG_INPUT_EMU10K1
#undef  CONFIG_INPUT_SERIO
#undef  CONFIG_INPUT_SERPORT

/*
 * Joysticks
 */
#undef  CONFIG_INPUT_ANALOG
#undef  CONFIG_INPUT_A3D
#undef  CONFIG_INPUT_ADI
#undef  CONFIG_INPUT_COBRA
#undef  CONFIG_INPUT_GF2K
#undef  CONFIG_INPUT_GRIP
#undef  CONFIG_INPUT_INTERACT
#undef  CONFIG_INPUT_TMDC
#undef  CONFIG_INPUT_SIDEWINDER
#undef  CONFIG_INPUT_IFORCE_USB
#undef  CONFIG_INPUT_IFORCE_232
#undef  CONFIG_INPUT_WARRIOR
#undef  CONFIG_INPUT_MAGELLAN
#undef  CONFIG_INPUT_SPACEORB
#undef  CONFIG_INPUT_SPACEBALL
#undef  CONFIG_INPUT_STINGER
#undef  CONFIG_INPUT_DB9
#undef  CONFIG_INPUT_GAMECON
#undef  CONFIG_INPUT_TURBOGRAFX
#undef  CONFIG_QIC02_TAPE
#undef  CONFIG_IPMI_HANDLER
#undef  CONFIG_IPMI_PANIC_EVENT
#undef  CONFIG_IPMI_DEVICE_INTERFACE
#undef  CONFIG_IPMI_KCS
#undef  CONFIG_IPMI_WATCHDOG

/*
 * Watchdog Cards
 */
#undef  CONFIG_WATCHDOG
#undef  CONFIG_SCx200_GPIO
#undef  CONFIG_AMD_RNG
#undef  CONFIG_INTEL_RNG
#define CONFIG_INTEL_RNG_MODULE 1
#undef  CONFIG_AMD_PM768
#undef  CONFIG_NVRAM
#define CONFIG_NVRAM_MODULE 1
#undef  CONFIG_RTC
#define CONFIG_RTC_MODULE 1
#undef  CONFIG_DTLK
#undef  CONFIG_R3964
#undef  CONFIG_APPLICOM
#undef  CONFIG_SONYPI

/*
 * Ftape, the floppy tape device driver
 */
#undef  CONFIG_FTAPE
#define CONFIG_AGP 1
#define CONFIG_AGP_INTEL 1
#define CONFIG_AGP_I810 1
#undef  CONFIG_AGP_VIA
#undef  CONFIG_AGP_AMD
#undef  CONFIG_AGP_AMD_8151
#define CONFIG_AGP_SIS 1
#define CONFIG_AGP_ALI 1
#undef  CONFIG_AGP_SWORKS
#undef  CONFIG_AGP_NVIDIA
#define CONFIG_DRM 1
#undef  CONFIG_DRM_OLD

/*
 * DRM 4.1 drivers
 */
#define CONFIG_DRM_NEW 1
#undef  CONFIG_DRM_TDFX
#undef  CONFIG_DRM_R128
#define CONFIG_DRM_RADEON 1
#undef  CONFIG_DRM_I810
#undef  CONFIG_DRM_I810_XFREE_41
#undef  CONFIG_DRM_I830
#undef  CONFIG_DRM_MGA
#undef  CONFIG_DRM_SIS

/*
 * PCMCIA character devices
 */
#undef  CONFIG_PCMCIA_SERIAL_CS
#undef  CONFIG_SYNCLINK_CS
#undef  CONFIG_MWAVE

/*
 * Multimedia devices
 */
#undef  CONFIG_VIDEO_DEV

/*
 * File systems
 */
#define CONFIG_QUOTA 1
#undef  CONFIG_QFMT_V2
#undef  CONFIG_AUTOFS_FS
#define CONFIG_AUTOFS4_FS 1
#undef  CONFIG_REISERFS_FS
#undef  CONFIG_REISERFS_CHECK
#undef  CONFIG_REISERFS_PROC_INFO
#undef  CONFIG_ADFS_FS
#undef  CONFIG_ADFS_FS_RW
#undef  CONFIG_AFFS_FS
#undef  CONFIG_HFS_FS
#undef  CONFIG_HFSPLUS_FS
#undef  CONFIG_BEFS_FS
#undef  CONFIG_BEFS_DEBUG
#undef  CONFIG_BFS_FS
#define CONFIG_EXT3_FS 1
#define CONFIG_JBD 1
#define CONFIG_JBD_DEBUG 1
#undef  CONFIG_FAT_FS
#define CONFIG_FAT_FS_MODULE 1
#undef  CONFIG_MSDOS_FS
#define CONFIG_MSDOS_FS_MODULE 1
#undef  CONFIG_UMSDOS_FS
#undef  CONFIG_VFAT_FS
#define CONFIG_VFAT_FS_MODULE 1
#undef  CONFIG_EFS_FS
#undef  CONFIG_JFFS_FS
#undef  CONFIG_JFFS2_FS
#undef  CONFIG_CRAMFS
#define CONFIG_CRAMFS_MODULE 1
#define CONFIG_TMPFS 1
#define CONFIG_RAMFS 1
#undef  CONFIG_ISO9660_FS
#define CONFIG_ISO9660_FS_MODULE 1
#define CONFIG_JOLIET 1
#undef  CONFIG_ZISOFS
#undef  CONFIG_JFS_FS
#undef  CONFIG_JFS_DEBUG
#undef  CONFIG_JFS_STATISTICS
#undef  CONFIG_MINIX_FS
#define CONFIG_MINIX_FS_MODULE 1
#undef  CONFIG_VXFS_FS
#undef  CONFIG_NTFS_FS
#define CONFIG_NTFS_FS_MODULE 1
#undef  CONFIG_NTFS_RW
#undef  CONFIG_HPFS_FS
#define CONFIG_HPFS_FS_MODULE 1
#define CONFIG_PROC_FS 1
#undef  CONFIG_DEVFS_FS
#undef  CONFIG_DEVFS_MOUNT
#undef  CONFIG_DEVFS_DEBUG
#define CONFIG_DEVPTS_FS 1
#undef  CONFIG_QNX4FS_FS
#undef  CONFIG_QNX4FS_RW
#undef  CONFIG_ROMFS_FS
#define CONFIG_ROMFS_FS_MODULE 1
#define CONFIG_EXT2_FS 1
#undef  CONFIG_SYSV_FS
#undef  CONFIG_UDF_FS
#undef  CONFIG_UDF_RW
#undef  CONFIG_UFS_FS
#undef  CONFIG_UFS_FS_WRITE

/*
 * Network File Systems
 */
#undef  CONFIG_CODA_FS
#undef  CONFIG_INTERMEZZO_FS
#undef  CONFIG_NFS_FS
#define CONFIG_NFS_FS_MODULE 1
#define CONFIG_NFS_V3 1
#undef  CONFIG_NFS_DIRECTIO
#undef  CONFIG_ROOT_NFS
#undef  CONFIG_NFSD
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V3 1
#define CONFIG_NFSD_TCP 1
#undef  CONFIG_SUNRPC
#define CONFIG_SUNRPC_MODULE 1
#undef  CONFIG_LOCKD
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#undef  CONFIG_SMB_FS
#define CONFIG_SMB_FS_MODULE 1
#undef  CONFIG_SMB_NLS_DEFAULT
#undef  CONFIG_NCP_FS
#undef  CONFIG_NCPFS_PACKET_SIGNING
#undef  CONFIG_NCPFS_IOCTL_LOCKING
#undef  CONFIG_NCPFS_STRONG
#undef  CONFIG_NCPFS_NFS_NS
#undef  CONFIG_NCPFS_OS2_NS
#undef  CONFIG_NCPFS_SMALLDOS
#undef  CONFIG_NCPFS_NLS
#undef  CONFIG_NCPFS_EXTRAS
#undef  CONFIG_ZISOFS_FS

/*
 * Partition Types
 */
#undef  CONFIG_PARTITION_ADVANCED
#define CONFIG_MSDOS_PARTITION 1
#define CONFIG_SMB_NLS 1
#define CONFIG_NLS 1

/*
 * Native Language Support
 */
#define CONFIG_NLS_DEFAULT "iso8859-1"
#undef  CONFIG_NLS_CODEPAGE_437
#define CONFIG_NLS_CODEPAGE_437_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_737
#undef  CONFIG_NLS_CODEPAGE_775
#undef  CONFIG_NLS_CODEPAGE_850
#undef  CONFIG_NLS_CODEPAGE_852
#undef  CONFIG_NLS_CODEPAGE_855
#undef  CONFIG_NLS_CODEPAGE_857
#undef  CONFIG_NLS_CODEPAGE_860
#undef  CONFIG_NLS_CODEPAGE_861
#undef  CONFIG_NLS_CODEPAGE_862
#undef  CONFIG_NLS_CODEPAGE_863
#undef  CONFIG_NLS_CODEPAGE_864
#undef  CONFIG_NLS_CODEPAGE_865
#undef  CONFIG_NLS_CODEPAGE_866
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_869
#undef  CONFIG_NLS_CODEPAGE_936
#undef  CONFIG_NLS_CODEPAGE_950
#undef  CONFIG_NLS_CODEPAGE_932
#undef  CONFIG_NLS_CODEPAGE_949
#undef  CONFIG_NLS_CODEPAGE_874
#undef  CONFIG_NLS_ISO8859_8
#undef  CONFIG_NLS_CODEPAGE_1250
#undef  CONFIG_NLS_CODEPAGE_1251
#define CONFIG_NLS_CODEPAGE_1251_MODULE 1
#undef  CONFIG_NLS_ISO8859_1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#undef  CONFIG_NLS_ISO8859_2
#undef  CONFIG_NLS_ISO8859_3
#undef  CONFIG_NLS_ISO8859_4
#undef  CONFIG_NLS_ISO8859_5
#define CONFIG_NLS_ISO8859_5_MODULE 1
#undef  CONFIG_NLS_ISO8859_6
#undef  CONFIG_NLS_ISO8859_7
#undef  CONFIG_NLS_ISO8859_9
#undef  CONFIG_NLS_ISO8859_13
#undef  CONFIG_NLS_ISO8859_14
#undef  CONFIG_NLS_ISO8859_15
#undef  CONFIG_NLS_KOI8_R
#define CONFIG_NLS_KOI8_R_MODULE 1
#undef  CONFIG_NLS_KOI8_U
#define CONFIG_NLS_KOI8_U_MODULE 1
#undef  CONFIG_NLS_UTF8
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Console drivers
 */
#define CONFIG_VGA_CONSOLE 1
#define CONFIG_VIDEO_SELECT 1
#undef  CONFIG_MDA_CONSOLE

/*
 * Frame-buffer support
 */
#undef  CONFIG_FB

/*
 * Sound
 */
#undef  CONFIG_SOUND
#define CONFIG_SOUND_MODULE 1
#undef  CONFIG_SOUND_ALI5455
#define CONFIG_SOUND_ALI5455_MODULE 1
#undef  CONFIG_SOUND_BT878
#define CONFIG_SOUND_BT878_MODULE 1
#undef  CONFIG_SOUND_CMPCI
#define CONFIG_SOUND_CMPCI_MODULE 1
#undef  CONFIG_SOUND_CMPCI_FM
#undef  CONFIG_SOUND_CMPCI_MIDI
#undef  CONFIG_SOUND_CMPCI_JOYSTICK
#undef  CONFIG_SOUND_CMPCI_CM8738
#undef  CONFIG_SOUND_EMU10K1
#define CONFIG_SOUND_EMU10K1_MODULE 1
#define CONFIG_MIDI_EMU10K1 1
#undef  CONFIG_SOUND_FUSION
#define CONFIG_SOUND_FUSION_MODULE 1
#undef  CONFIG_SOUND_CS4281
#define CONFIG_SOUND_CS4281_MODULE 1
#undef  CONFIG_SOUND_ES1370
#define CONFIG_SOUND_ES1370_MODULE 1
#undef  CONFIG_SOUND_ES1371
#define CONFIG_SOUND_ES1371_MODULE 1
#undef  CONFIG_SOUND_ESSSOLO1
#define CONFIG_SOUND_ESSSOLO1_MODULE 1
#undef  CONFIG_SOUND_MAESTRO
#define CONFIG_SOUND_MAESTRO_MODULE 1
#undef  CONFIG_SOUND_MAESTRO3
#define CONFIG_SOUND_MAESTRO3_MODULE 1
#undef  CONFIG_SOUND_FORTE
#define CONFIG_SOUND_FORTE_MODULE 1
#undef  CONFIG_SOUND_ICH
#define CONFIG_SOUND_ICH_MODULE 1
#undef  CONFIG_SOUND_RME96XX
#define CONFIG_SOUND_RME96XX_MODULE 1
#undef  CONFIG_SOUND_SONICVIBES
#define CONFIG_SOUND_SONICVIBES_MODULE 1
#undef  CONFIG_SOUND_TRIDENT
#define CONFIG_SOUND_TRIDENT_MODULE 1
#undef  CONFIG_SOUND_MSNDCLAS
#undef  CONFIG_SOUND_MSNDPIN
#undef  CONFIG_SOUND_VIA82CXXX
#define CONFIG_SOUND_VIA82CXXX_MODULE 1
#define CONFIG_MIDI_VIA82CXXX 1
#undef  CONFIG_SOUND_OSS
#define CONFIG_SOUND_OSS_MODULE 1
#define CONFIG_SOUND_TRACEINIT 1
#undef  CONFIG_SOUND_DMAP
#undef  CONFIG_SOUND_AD1816
#define CONFIG_SOUND_AD1816_MODULE 1
#undef  CONFIG_SOUND_AD1889
#define CONFIG_SOUND_AD1889_MODULE 1
#undef  CONFIG_SOUND_SGALAXY
#define CONFIG_SOUND_SGALAXY_MODULE 1
#undef  CONFIG_SOUND_ADLIB
#define CONFIG_SOUND_ADLIB_MODULE 1
#undef  CONFIG_SOUND_ACI_MIXER
#define CONFIG_SOUND_ACI_MIXER_MODULE 1
#undef  CONFIG_SOUND_CS4232
#define CONFIG_SOUND_CS4232_MODULE 1
#undef  CONFIG_SOUND_SSCAPE
#define CONFIG_SOUND_SSCAPE_MODULE 1
#undef  CONFIG_SOUND_GUS
#define CONFIG_SOUND_GUS_MODULE 1
#undef  CONFIG_SOUND_GUS16
#undef  CONFIG_SOUND_GUSMAX
#undef  CONFIG_SOUND_VMIDI
#define CONFIG_SOUND_VMIDI_MODULE 1
#undef  CONFIG_SOUND_TRIX
#define CONFIG_SOUND_TRIX_MODULE 1
#undef  CONFIG_SOUND_MSS
#define CONFIG_SOUND_MSS_MODULE 1
#undef  CONFIG_SOUND_MPU401
#define CONFIG_SOUND_MPU401_MODULE 1
#undef  CONFIG_SOUND_NM256
#undef  CONFIG_SOUND_MAD16
#define CONFIG_SOUND_MAD16_MODULE 1
#undef  CONFIG_MAD16_OLDCARD
#undef  CONFIG_SOUND_PAS
#define CONFIG_SOUND_PAS_MODULE 1
#undef  CONFIG_PAS_JOYSTICK
#undef  CONFIG_SOUND_PSS
#undef  CONFIG_SOUND_SB
#define CONFIG_SOUND_SB_MODULE 1
#undef  CONFIG_SOUND_AWE32_SYNTH
#define CONFIG_SOUND_AWE32_SYNTH_MODULE 1
#undef  CONFIG_SOUND_KAHLUA
#undef  CONFIG_SOUND_WAVEFRONT
#undef  CONFIG_SOUND_MAUI
#undef  CONFIG_SOUND_YM3812
#define CONFIG_SOUND_YM3812_MODULE 1
#undef  CONFIG_SOUND_OPL3SA1
#define CONFIG_SOUND_OPL3SA1_MODULE 1
#undef  CONFIG_SOUND_OPL3SA2
#define CONFIG_SOUND_OPL3SA2_MODULE 1
#undef  CONFIG_SOUND_YMFPCI
#define CONFIG_SOUND_YMFPCI_MODULE 1
#undef  CONFIG_SOUND_YMFPCI_LEGACY
#undef  CONFIG_SOUND_UART6850
#define CONFIG_SOUND_UART6850_MODULE 1
#undef  CONFIG_SOUND_AEDSP16
#undef  CONFIG_SOUND_TVMIXER

/*
 * USB support
 */
#undef  CONFIG_USB
#define CONFIG_USB_MODULE 1
#define CONFIG_USB_DEBUG 1

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#define CONFIG_USB_BANDWIDTH 1

/*
 * USB Host Controller Drivers
 */
#undef  CONFIG_USB_EHCI_HCD
#define CONFIG_USB_EHCI_HCD_MODULE 1
#undef  CONFIG_USB_UHCI
#undef  CONFIG_USB_UHCI_ALT
#define CONFIG_USB_UHCI_ALT_MODULE 1
#undef  CONFIG_USB_OHCI
#define CONFIG_USB_OHCI_MODULE 1

/*
 * USB Device Class drivers
 */
#undef  CONFIG_USB_AUDIO
#define CONFIG_USB_AUDIO_MODULE 1
#undef  CONFIG_USB_EMI26
#define CONFIG_USB_EMI26_MODULE 1

/*
 *   USB Bluetooth can only be used with disabled Bluetooth subsystem
 */
#undef  CONFIG_USB_MIDI
#define CONFIG_USB_MIDI_MODULE 1
#undef  CONFIG_USB_STORAGE
#define CONFIG_USB_STORAGE_MODULE 1
#define CONFIG_USB_STORAGE_DEBUG 1
#define CONFIG_USB_STORAGE_DATAFAB 1
#define CONFIG_USB_STORAGE_FREECOM 1
#define CONFIG_USB_STORAGE_ISD200 1
#define CONFIG_USB_STORAGE_DPCM 1
#define CONFIG_USB_STORAGE_HP8200e 1
#define CONFIG_USB_STORAGE_SDDR09 1
#define CONFIG_USB_STORAGE_SDDR55 1
#define CONFIG_USB_STORAGE_JUMPSHOT 1
#undef  CONFIG_USB_ACM
#define CONFIG_USB_ACM_MODULE 1
#undef  CONFIG_USB_PRINTER
#define CONFIG_USB_PRINTER_MODULE 1

/*
 * USB Human Interface Devices (HID)
 */
#undef  CONFIG_USB_HID
#define CONFIG_USB_HID_MODULE 1
#define CONFIG_USB_HIDINPUT 1
#define CONFIG_USB_HIDDEV 1
#undef  CONFIG_USB_KBD
#define CONFIG_USB_KBD_MODULE 1
#undef  CONFIG_USB_MOUSE
#define CONFIG_USB_MOUSE_MODULE 1
#undef  CONFIG_USB_AIPTEK
#define CONFIG_USB_AIPTEK_MODULE 1
#undef  CONFIG_USB_WACOM
#define CONFIG_USB_WACOM_MODULE 1
#undef  CONFIG_USB_KBTAB
#define CONFIG_USB_KBTAB_MODULE 1
#undef  CONFIG_USB_POWERMATE
#define CONFIG_USB_POWERMATE_MODULE 1

/*
 * USB Imaging devices
 */
#undef  CONFIG_USB_DC2XX
#define CONFIG_USB_DC2XX_MODULE 1
#undef  CONFIG_USB_MDC800
#define CONFIG_USB_MDC800_MODULE 1
#undef  CONFIG_USB_SCANNER
#define CONFIG_USB_SCANNER_MODULE 1
#undef  CONFIG_USB_MICROTEK
#define CONFIG_USB_MICROTEK_MODULE 1
#undef  CONFIG_USB_HPUSBSCSI
#define CONFIG_USB_HPUSBSCSI_MODULE 1

/*
 * USB Multimedia devices
 */

/*
 *   Video4Linux support is needed for USB Multimedia device support
 */

/*
 * USB Network adaptors
 */
#undef  CONFIG_USB_PEGASUS
#undef  CONFIG_USB_RTL8150
#undef  CONFIG_USB_KAWETH
#undef  CONFIG_USB_CATC
#undef  CONFIG_USB_AX8817X
#undef  CONFIG_USB_CDCETHER
#undef  CONFIG_USB_USBNET

/*
 * USB port drivers
 */
#undef  CONFIG_USB_USS720

/*
 * USB Serial Converter support
 */
#undef  CONFIG_USB_SERIAL

/*
 * USB Miscellaneous drivers
 */
#undef  CONFIG_USB_RIO500
#undef  CONFIG_USB_AUERSWALD
#undef  CONFIG_USB_TIGL
#undef  CONFIG_USB_BRLVGER
#undef  CONFIG_USB_LCD
#define CONFIG_USB_LCD_MODULE 1

/*
 * Bluetooth support
 */
#undef  CONFIG_BLUEZ
#define CONFIG_BLUEZ_MODULE 1
#undef  CONFIG_BLUEZ_L2CAP
#define CONFIG_BLUEZ_L2CAP_MODULE 1
#undef  CONFIG_BLUEZ_SCO
#define CONFIG_BLUEZ_SCO_MODULE 1
#undef  CONFIG_BLUEZ_RFCOMM
#define CONFIG_BLUEZ_RFCOMM_MODULE 1
#define CONFIG_BLUEZ_RFCOMM_TTY 1
#undef  CONFIG_BLUEZ_BNEP
#define CONFIG_BLUEZ_BNEP_MODULE 1
#define CONFIG_BLUEZ_BNEP_MC_FILTER 1
#define CONFIG_BLUEZ_BNEP_PROTO_FILTER 1

/*
 * Bluetooth device drivers
 */
#undef  CONFIG_BLUEZ_HCIUSB
#define CONFIG_BLUEZ_HCIUSB_MODULE 1
#define CONFIG_BLUEZ_USB_SCO 1
#define CONFIG_BLUEZ_USB_ZERO_PACKET 1
#undef  CONFIG_BLUEZ_HCIUART
#define CONFIG_BLUEZ_HCIUART_MODULE 1
#define CONFIG_BLUEZ_HCIUART_H4 1
#define CONFIG_BLUEZ_HCIUART_BCSP 1
#define CONFIG_BLUEZ_HCIUART_BCSP_TXCRC 1
#undef  CONFIG_BLUEZ_HCIBFUSB
#define CONFIG_BLUEZ_HCIBFUSB_MODULE 1
#undef  CONFIG_BLUEZ_HCIDTL1
#define CONFIG_BLUEZ_HCIDTL1_MODULE 1
#undef  CONFIG_BLUEZ_HCIBT3C
#define CONFIG_BLUEZ_HCIBT3C_MODULE 1
#undef  CONFIG_BLUEZ_HCIBLUECARD
#define CONFIG_BLUEZ_HCIBLUECARD_MODULE 1
#undef  CONFIG_BLUEZ_HCIBTUART
#define CONFIG_BLUEZ_HCIBTUART_MODULE 1
#undef  CONFIG_BLUEZ_HCIVHCI
#define CONFIG_BLUEZ_HCIVHCI_MODULE 1

/*
 * Security options
 */
#define CONFIG_HARDEN_STACK 1
#define CONFIG_HARDEN_STACK_SMART 1
#define CONFIG_HARDEN_LINK 1
#define CONFIG_HARDEN_FIFO 1
#define CONFIG_HARDEN_PROC 1
#define CONFIG_HARDEN_RLIMIT_NPROC 1
#undef  CONFIG_HARDEN_SHM

/*
 * Kernel hacking
 */
#define CONFIG_DEBUG_KERNEL 1
#undef  CONFIG_DEBUG_STACKOVERFLOW
#undef  CONFIG_DEBUG_HIGHMEM
#undef  CONFIG_DEBUG_SLAB
#undef  CONFIG_DEBUG_IOVIRT
#define CONFIG_MAGIC_SYSRQ 1
#undef  CONFIG_DEBUG_SPINLOCK
#undef  CONFIG_FRAME_POINTER

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#undef  CONFIG_CRYPTO_NULL
#define CONFIG_CRYPTO_NULL_MODULE 1
#undef  CONFIG_CRYPTO_MD4
#define CONFIG_CRYPTO_MD4_MODULE 1
#undef  CONFIG_CRYPTO_MD5
#define CONFIG_CRYPTO_MD5_MODULE 1
#undef  CONFIG_CRYPTO_SHA1
#define CONFIG_CRYPTO_SHA1_MODULE 1
#undef  CONFIG_CRYPTO_SHA256
#define CONFIG_CRYPTO_SHA256_MODULE 1
#undef  CONFIG_CRYPTO_SHA512
#define CONFIG_CRYPTO_SHA512_MODULE 1
#undef  CONFIG_CRYPTO_DES
#define CONFIG_CRYPTO_DES_MODULE 1
#undef  CONFIG_CRYPTO_BLOWFISH
#define CONFIG_CRYPTO_BLOWFISH_MODULE 1
#undef  CONFIG_CRYPTO_TWOFISH
#define CONFIG_CRYPTO_TWOFISH_MODULE 1
#undef  CONFIG_CRYPTO_SERPENT
#define CONFIG_CRYPTO_SERPENT_MODULE 1
#undef  CONFIG_CRYPTO_AES
#define CONFIG_CRYPTO_AES_MODULE 1
#undef  CONFIG_CRYPTO_DEFLATE
#define CONFIG_CRYPTO_DEFLATE_MODULE 1
#undef  CONFIG_CRYPTO_TEST
#define CONFIG_CRYPTO_TEST_MODULE 1

/*
 * Library routines
 */
#undef  CONFIG_CRC32
#define CONFIG_CRC32_MODULE 1
#undef  CONFIG_ZLIB_INFLATE
#define CONFIG_ZLIB_INFLATE_MODULE 1
#undef  CONFIG_ZLIB_DEFLATE
#define CONFIG_ZLIB_DEFLATE_MODULE 1
