#! /bin/sh
# $Id$

PREPARE="$1"
TARGET="$2"

[ "${TARGET}" != "" ] || exit 0
[ -d "config.d" ] || exit 0
cd "config.d"
for i in *.cfg
do
  j="${TARGET}/$i"
  if [ "${PRESERVE}" = 1 ]
  then
    if [ -f "$j" ]
    then
      if ! diff -q "$i" "$j" >/dev/null 2>&1
      then
        rm -f "$j.new"
        install -m 0755 "$i" "$j.new"
      fi
    else
      install -m 0755 "$i" "$j"
    fi
  else
    if [ -f "$j" ]
    then
      if ! diff -q "$i" "$j" >/dev/null 2>&1
      then
        rm -f "$j.old"
        mv "$j" "$j.old"
        install -m 0755 "$i" "$j"
      fi
    else
      install -m 0755 "$i" "$j"
    fi
  fi
done

# if [ -d "config.d" ]; then cd config.d; for i in *.cfg; do j="${DESTDIR}${LANG_CONFIG_DIR}/$$i"; if [ "${PRESERVE}" = 1 ]; then if [ -f "$$j" ]; then if ! diff -q "$$i" "$$j" >/dev/null 2>&1 else : fi; else : fi; done; fi; true
